# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4246d50af3f63aa3732f8f58debabc1913bedf8e1584d98cf35b016c4d814f8271b0af5b1e3c9e26b10c4469ec7eb6b22e372bc5d8c12ef78c0396dd0ca0501b

test:
  secret_key_base: 0bd61e350282552e81fcca6872de5997ab8b0403fd9ec519a74f4880f5f35ec5722a2b9a4e791ae801e71e0bceb36d1a0e74d343e6bea7cb5daebb80b7b05977

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
